spring.application.name=securenotes

# ========================
# Google OAuth2 Settings
# ========================
spring.security.oauth2.client.registration.google.client-id=1016631877079-8l8g7eukmtki76oa15m3nf8ceo2su7qt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email
#spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.redirect-uri=http://secure-notes-backend-production.up.railway.app/login/oauth2/code/google

